import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Header";
import { PostProvider } from '@/app/context/PostContext';
import { Suspense } from "react";
import Loading from "./loading";

export const metadata: Metadata = {
  title: "NXT Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <PostProvider>
          <Suspense fallback={<Loading/>} >  
            <Header/>
           {children}
          </Suspense> 
        </PostProvider>
      </body>
    </html>
  );
}
