import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Header";
import { PostProvider } from '@/app/context/PostContext';

export const metadata: Metadata = {
  title: "NXT Nlog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <PostProvider>
          <Header/>
          {children}
        </PostProvider>
      </body>
    </html>
  );
}
